image:                                                               node:latest

include:
  - template:                                                        Code-Quality.gitlab-ci.yml

stages:
  - npm
  - test
  - deploy

default:
    before_script:
        - echo "Starting job..."
    after_script:
        - echo "Job executed successfully"

npm:
    stage:                                                           npm
    script:
        - npm config set registry ${CI_NPM_REGISTRY}
        - npm install
    cache:
        paths:
            - node_modules/
    artifacts:
        expire_in:                                                   1 hour
        when:                                                        on_success
        paths:
            - node_modules/

test_db:
    stage:                                                           test
    when:                                                            on_success
    dependencies:
        - npm
    script:
        - node ./models/user.js

test:
    stage:                                                           test
    when:                                                            on_success
    dependencies:
        - npm
    script:
        - npm test


code_quality:
  stage:                                                             test
  image:                                                             docker:stable
  variables:
    DOCKER_DRIVER:                                                   overlay2
  allow_failure:                                                     true
  services:
  - docker:stable-dind
  script:
  - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
  - docker run
      --env SOURCE_CODE="$PWD"
      --volume "$PWD":/code
      --volume /var/run/docker.sock:/var/run/docker.sock
      "registry.gitlab.com/gitlab-org/security-products/codequality:12-3-stable" /code
  artifacts:
    paths:                                                           [gl-code-quality-report.json]


trigger_build:
  stage:                                                             deploy
  script:
    - "curl -X POST -F token=7e868b65456e09d9f2f986f4987922 -F ref=master https://gitlab.com/api/v4/projects/22562690/trigger/pipeline"
